### ISSUE TITLE
Permission issue when building the Docker image 

### ISSUE THREAD

**Issue by EvgenyInberg** [awslabs/containers-cost-allocation-dashboard#1]
@udid-aws Hi 
During image build process the following error is being generated: 
```
Step 15/42 : RUN pyinstaller -F main.py --specpath . --hidden-import pyarrow.vendored.version --collect-all dateutil
 ---> Running in 57426d564593
189 INFO: PyInstaller: 6.3.0
190 INFO: Python: 3.12.1
191 INFO: Platform: Linux-4.14.276-211.499.amzn2.x86_64-x86_64-with-glibc2.36
Traceback (most recent call last):
  File "/home/nonroot/.local/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nonroot/.local/lib/python3.12/site-packages/PyInstaller/__main__.py", line 214, in _console_script_run
    run()
  File "/home/nonroot/.local/lib/python3.12/site-packages/PyInstaller/__main__.py", line 195, in run
    spec_file = run_makespec(**vars(args))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nonroot/.local/lib/python3.12/site-packages/PyInstaller/__main__.py", line 62, in run_makespec
    spec_file = PyInstaller.building.makespec.main(filenames, **opts)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nonroot/.local/lib/python3.12/site-packages/PyInstaller/building/makespec.py", line 838, in main
    with open(specfnm, 'w', encoding='utf-8') as specfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: './main.spec'
The command '/bin/sh -c pyinstaller -F main.py --specpath . --hidden-import pyarrow.vendored.version --collect-all dateutil' returned a non-zero code: 1
```

**Comment by udid-aws** [comment]
Hi @EvgenyInberg

Can you please try adding the below lines between lines 43 and 44 of the `Dockerfile`:
```dockerfile
RUN chown -R nonroot:nonroot /home/nonroot/app
RUN chmod -R 755 /home/nonroot/app
```

Before (partial snippet):

```dockerfile
WORKDIR /home/nonroot/app
COPY --chown=nonroot:nonroot main.py .
RUN pyinstaller -F main.py --specpath . --hidden-import pyarrow.vendored.version --collect-all dateutil
```

After (partial snippet):
```dockerfile
WORKDIR /home/nonroot/app
RUN chown -R nonroot:nonroot /home/nonroot/app
RUN chmod -R 755 /home/nonroot/app
COPY --chown=nonroot:nonroot main.py .
RUN pyinstaller -F main.py --specpath . --hidden-import pyarrow.vendored.version --collect-all dateutil
```

Can you please try it and let me know if it solves the issue?

**Comment by EvgenyInberg** [comment]
@udid-aws Unfortunately not working 

```
Step 14/44 : RUN chown -R nonroot:nonroot /home/nonroot/app
 ---> Running in 46f4b303a5c3
chown: changing ownership of '/home/nonroot/app': Operation not permitted
The command '/bin/sh -c chown -R nonroot:nonroot /home/nonroot/app' returned a non-zero code: 1
```

**Comment by udid-aws** [comment]
@EvgenyInberg
Okay, I'll have to recreate it. I'm building on an EC2 running Ubuntu 20.04, and I'm using `sudo` when running the `docker build` command.
I didn't encounter this issue, and I guess it could be related to the user who's running the `docker build` command.
Can you share the following, so I can recreate it as closer to your setup as possible:

* On which OS and version are you building, and on which platform (EC2, or other)?
* Did you use `sudo`?
* What's the exact full `docker` command you used that ended up with this error?

**Comment by EvgenyInberg** [comment]
@udid-aws I added the following to the Docker file which solved the permissions issue: 
```
USER root
RUN chown -R nonroot:nonroot /home/nonroot/app
RUN chmod -R 755 /home/nonroot/app
USER nonroot
```
However now I have the following error: 
```
Step 43/46 : FROM copy_so_$TARGETARCH
invalid reference format
```

I am building this docker inside a aml2 Docker container. 
The build command is executed with root and I am using the simple `docker build -t <registry_url>/<repo>:<tag> .`
The error persisted when executing the build command with `--platform linux/amd64` param as well.

**Comment by udid-aws** [comment]
@EvgenyInberg, first, thanks for sharing the solution to solve the permissions issue. I'll try to find one that doesn't include switching to root and then to nonroot again, because at the beginning it's already root. I'll update on this.
As for the `invalid reference format` error, it seems that the `TARGETARCH` arg isn't picking up for some reason.
The idea here was to support both AMD64 and ARM64 images, and based on the `TARGETARCH` arg value, the Docker build process triggers the relevant build stage.
In your case the `TARGETARCH` arg value should be `amd64`, so the last build stage should become `FROM copy_so_amd64`, which should trigger the build stage on line 74 and copy the amd64 binaries to the scratch image.
When I'm building this on Ubuntu, it works. I'll try to recreate it like in your case, in AL2, and will update.
In the meantime, to build the image, please manually change line 128 from `FROM copy_so_$TARGETARCH` to `FROM copy_so_amd64`, this should solve it.
Please let me know how it goes

**Comment by udid-aws** [comment]
@EvgenyInberg, I recreated both issues on an AL2 EC2 instance, and I'm now focusing on the `invalid reference format` error.
So far I couldn't find why docker build isn't picking up the `TARGETARCH` value, and I'm still checking.
In the meantime, I tried with AL2023 EC2 instance with the original Dockerfile, without making any of the changes mentioned in the previous comments.
The build was successful and I didn't see the permissions error and also didn't see the `invalid reference format` error.
Can you run the docker build on AL2023 EC2 instance instead (or container, I see you tried building the image inside an AL2 container), or must you run the docker build on AL2?

**Comment by udid-aws** [comment]
@EvgenyInberg, problem found:
The latest Docker version for AL2 is 20.10.25, where [BuildKit](https://docs.docker.com/build/buildkit/) was still disabled by default.
The `TARGETARCH` arg is only available when BuildKit is being used.
On my AL2023 and Ubuntu 20.24 instances had Docker version higher than 23.0, where BuildKit is the default builder.
Once I enabled BuildKit according to the instructions in the above link, both the permissions issue and the `TARGETARCH` issue (that caused the `invalid reference format` error) were resolved.
I'm now running seeing another error when building the image on AL2 using Docker 20.10.25:
```docker
 => ERROR [stage-4 1/3] COPY --from=build --chown=nonroot:nonroot /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6                                                                                                                                          0.0s
------
 > [stage-4 1/3] COPY --from=build --chown=nonroot:nonroot /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6:
------
open /var/lib/docker/overlay2/howmpi8rp243jf8yp5624vyv9/diff/etc/group: no such file or directory
```

I'm still not sure what the issue is (Docker restart and host restart don't solve it), and it doesn't happen when building on my Ubuntu 20.04 or AL2023 instances.
It might be an issue local to my setup though.

Can you please enable BuildKit, try to build again, and see if it's successful or you're seeing the same new error I see now?

**Comment by udid-aws** [comment]
@EvgenyInberg, I have a solution for the above latest error (thanks to Docker community on Slack).
Add the below line:
```docker
COPY --from=build /etc/group /etc/group
```

After this line:
```docker
COPY --from=build /etc/passwd /etc/passwd
```

So, to summarize:

* Enable BuildKit as mentioned in the [BuildKit Docker doc](https://docs.docker.com/build/buildkit/)
This should solve both the permissions issue and the `invalid reference format` error without any changes in the original Dockerfile
* If you're then seeing the error mentioned in [this comment](https://github.com/awslabs/containers-cost-allocation-dashboard/issues/1#issuecomment-1954963463), please add the above line to the Dockerfile and retry

Please let me know if you can successfully build the image, or you're still seeing issues

**Comment by udid-aws** [comment]
@EvgenyInberg, did you review the recent comments? Can you check if the issue is resolved after implementing what I shared?

**Comment by EvgenyInberg** [comment]
@udid-aws Hi, 
Thanks for looking into this. 
I will test and update. 
Do you have a branch with these changes or maybe merged to master already?

**Comment by udid-aws** [comment]
@EvgenyInberg, I didn't merge the changes yet, but in my next update I'll include them.
There's only [one change in the Dockerfile](https://github.com/awslabs/containers-cost-allocation-dashboard/issues/1#issuecomment-1955074616), the other change should be on your Docker client (enabling BuildKit), and I'll update the docs to mention this requirement

**Comment by EvgenyInberg** [comment]
@udid-aws confirming that with these 2 modifications the build works.
Thanks

**Comment by udid-aws** [comment]
You're welcome. I'll keep the issue open until I push the changes to the main branch. I'll update
